// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUMemoryHeapInfo(
    public val `$mem`: MemorySegment,
) {
    public var properties: WGPUHeapPropertyFlags
        get() = (propertiesHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            propertiesHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public var size: uint64_t
        get() = (sizeHandle.get(this.`$mem`, 0L) as Long).toULong()
        set(`value`) {
            sizeHandle.set(this.`$mem`, 0L, value.toLong())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("properties"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.JAVA_LONG.withName("size"),
        ).withName("WGPUMemoryHeapInfo")

        @JvmField
        public val propertiesHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("properties"))

        @JvmField
        public val sizeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("size"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUMemoryHeapInfo =
            WGPUMemoryHeapInfo(alloc.allocate(layout))
    }
}
