// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUMultisampleState(
    public val `$mem`: MemorySegment,
) {
    public var nextInChain: Pointer<WGPUChainedStruct>
        get() = WGPUMultisampleState.nextInChainHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUMultisampleState.nextInChainHandle.set(this.`$mem`, 0L, value)
        }

    public var count: uint32_t
        get() = (WGPUMultisampleState.countHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            WGPUMultisampleState.countHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public var mask: uint32_t
        get() = (WGPUMultisampleState.maskHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            WGPUMultisampleState.maskHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public var alphaToCoverageEnabled: WGPUBool
        get() = (WGPUMultisampleState.alphaToCoverageEnabledHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            WGPUMultisampleState.alphaToCoverageEnabledHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUMultisampleState.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("nextInChain"),
            ValueLayout.JAVA_INT.withName("count"),
            ValueLayout.JAVA_INT.withName("mask"),
            ValueLayout.JAVA_INT.withName("alphaToCoverageEnabled"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("WGPUMultisampleState")

        @JvmField
        public val nextInChainHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("nextInChain"))

        @JvmField
        public val countHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("count"))

        @JvmField
        public val maskHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("mask"))

        @JvmField
        public val alphaToCoverageEnabledHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("alphaToCoverageEnabled"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUMultisampleState =
            WGPUMultisampleState(alloc.allocate(WGPUMultisampleState.layout))
    }
}
