// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUSharedFenceDXGISharedHandleExportInfo(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStructOut
        get() =
            WGPUChainedStructOut(
                WGPUSharedFenceDXGISharedHandleExportInfo.chainHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStructOut.layout.byteSize()
            )
        }

    public var handle: Pointer<Unit>
        get() = WGPUSharedFenceDXGISharedHandleExportInfo.handleHandle.get(this.`$mem`, 0L) as
                MemorySegment
        set(`value`) {
            WGPUSharedFenceDXGISharedHandleExportInfo.handleHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUSharedFenceDXGISharedHandleExportInfo.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStructOut.layout.withName("chain"),
            `$RuntimeHelper`.POINTER.withName("handle"),
        ).withName("WGPUSharedFenceDXGISharedHandleExportInfo")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val handleHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("handle"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUSharedFenceDXGISharedHandleExportInfo =
            WGPUSharedFenceDXGISharedHandleExportInfo(alloc.allocate(WGPUSharedFenceDXGISharedHandleExportInfo.layout))
    }
}
