// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*

@JvmInline
public value class WGPUSharedBufferMemoryImpl(
    public val `$mem`: MemorySegment,
) {
    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUSharedBufferMemoryImpl.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
        ).withName("WGPUSharedBufferMemoryImpl")

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUSharedBufferMemoryImpl =
            WGPUSharedBufferMemoryImpl(alloc.allocate(WGPUSharedBufferMemoryImpl.layout))
    }
}
