// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUCompareFunction(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    Never(0x00000001),
    Less(0x00000002),
    Equal(0x00000003),
    LessEqual(0x00000004),
    Greater(0x00000005),
    NotEqual(0x00000006),
    GreaterEqual(0x00000007),
    Always(0x00000008),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUCompareFunction::class.java,
            "fromInt",
            MethodType.methodType(WGPUCompareFunction::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUCompareFunction::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUCompareFunction = when (value) {
            0x00000000 -> Undefined
            0x00000001 -> Never
            0x00000002 -> Less
            0x00000003 -> Equal
            0x00000004 -> LessEqual
            0x00000005 -> Greater
            0x00000006 -> NotEqual
            0x00000007 -> GreaterEqual
            0x00000008 -> Always
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
