// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUSurfaceDescriptorFromWindowsHWND(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStruct
        get() =
            WGPUChainedStruct(
                WGPUSurfaceDescriptorFromWindowsHWND.chainHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStruct.layout.byteSize()
            )
        }

    public var hinstance: Pointer<Unit>
        get() = WGPUSurfaceDescriptorFromWindowsHWND.hinstanceHandle.get(this.`$mem`, 0L) as
                MemorySegment
        set(`value`) {
            WGPUSurfaceDescriptorFromWindowsHWND.hinstanceHandle.set(this.`$mem`, 0L, value)
        }

    public var hwnd: Pointer<Unit>
        get() = WGPUSurfaceDescriptorFromWindowsHWND.hwndHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUSurfaceDescriptorFromWindowsHWND.hwndHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUSurfaceDescriptorFromWindowsHWND.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStruct.layout.withName("chain"),
            `$RuntimeHelper`.POINTER.withName("hinstance"),
            `$RuntimeHelper`.POINTER.withName("hwnd"),
        ).withName("WGPUSurfaceDescriptorFromWindowsHWND")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val hinstanceHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("hinstance"))

        @JvmField
        public val hwndHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("hwnd"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUSurfaceDescriptorFromWindowsHWND =
            WGPUSurfaceDescriptorFromWindowsHWND(alloc.allocate(WGPUSurfaceDescriptorFromWindowsHWND.layout))
    }
}
