// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUChainedStruct(
    public val `$mem`: MemorySegment,
) {
    public var next: Pointer<WGPUChainedStruct>
        get() = WGPUChainedStruct.nextHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUChainedStruct.nextHandle.set(this.`$mem`, 0L, value)
        }

    public var sType: WGPUSType
        get() = WGPUSType.fromInt(WGPUChainedStruct.sTypeHandle.get(this.`$mem`, 0L) as Int)
        set(`value`) {
            WGPUChainedStruct.sTypeHandle.set(this.`$mem`, 0L, value.value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUChainedStruct.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("next"),
            ValueLayout.JAVA_INT.withName("sType"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("WGPUChainedStruct")

        @JvmField
        public val nextHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("next"))

        @JvmField
        public val sTypeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("sType"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUChainedStruct =
            WGPUChainedStruct(alloc.allocate(WGPUChainedStruct.layout))
    }
}
