// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUTextureAspect(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    All(0x00000001),
    StencilOnly(0x00000002),
    DepthOnly(0x00000003),
    Plane0Only(0x00000004),
    Plane1Only(0x00000005),
    Plane2Only(0x00000006),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUTextureAspect::class.java,
            "fromInt",
            MethodType.methodType(WGPUTextureAspect::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUTextureAspect::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUTextureAspect = when (value) {
            0x00000000 -> Undefined
            0x00000001 -> All
            0x00000002 -> StencilOnly
            0x00000003 -> DepthOnly
            0x00000004 -> Plane0Only
            0x00000005 -> Plane1Only
            0x00000006 -> Plane2Only
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
