// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUColorTargetStateExpandResolveTextureDawn(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStruct
        get() =
            WGPUChainedStruct(
                WGPUColorTargetStateExpandResolveTextureDawn.chainHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStruct.layout.byteSize()
            )
        }

    public var enabled: WGPUBool
        get() = (WGPUColorTargetStateExpandResolveTextureDawn.enabledHandle.get(this.`$mem`, 0L) as
                Int).toUInt()
        set(`value`) {
            WGPUColorTargetStateExpandResolveTextureDawn.enabledHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUColorTargetStateExpandResolveTextureDawn.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStruct.layout.withName("chain"),
            ValueLayout.JAVA_INT.withName("enabled"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("WGPUColorTargetStateExpandResolveTextureDawn")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val enabledHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("enabled"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUColorTargetStateExpandResolveTextureDawn =
            WGPUColorTargetStateExpandResolveTextureDawn(alloc.allocate(WGPUColorTargetStateExpandResolveTextureDawn.layout))
    }
}
