// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUTextureViewDimension(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    `1D`(0x00000001),
    `2D`(0x00000002),
    `2DArray`(0x00000003),
    Cube(0x00000004),
    CubeArray(0x00000005),
    `3D`(0x00000006),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUTextureViewDimension::class.java,
            "fromInt",
            MethodType.methodType(WGPUTextureViewDimension::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUTextureViewDimension::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUTextureViewDimension = when (value) {
            0x00000000 -> Undefined
            0x00000001 -> `1D`
            0x00000002 -> `2D`
            0x00000003 -> `2DArray`
            0x00000004 -> Cube
            0x00000005 -> CubeArray
            0x00000006 -> `3D`
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
