// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUBlendFactor(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    Zero(0x00000001),
    One(0x00000002),
    Src(0x00000003),
    OneMinusSrc(0x00000004),
    SrcAlpha(0x00000005),
    OneMinusSrcAlpha(0x00000006),
    Dst(0x00000007),
    OneMinusDst(0x00000008),
    DstAlpha(0x00000009),
    OneMinusDstAlpha(0x0000000a),
    SrcAlphaSaturated(0x0000000b),
    Constant(0x0000000c),
    OneMinusConstant(0x0000000d),
    Src1(0x0000000e),
    OneMinusSrc1(0x0000000f),
    Src1Alpha(0x00000010),
    OneMinusSrc1Alpha(0x00000011),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUBlendFactor::class.java,
            "fromInt",
            MethodType.methodType(WGPUBlendFactor::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUBlendFactor::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUBlendFactor = when (value) {
            0x00000000 -> Undefined
            0x00000001 -> Zero
            0x00000002 -> One
            0x00000003 -> Src
            0x00000004 -> OneMinusSrc
            0x00000005 -> SrcAlpha
            0x00000006 -> OneMinusSrcAlpha
            0x00000007 -> Dst
            0x00000008 -> OneMinusDst
            0x00000009 -> DstAlpha
            0x0000000a -> OneMinusDstAlpha
            0x0000000b -> SrcAlphaSaturated
            0x0000000c -> Constant
            0x0000000d -> OneMinusConstant
            0x0000000e -> Src1
            0x0000000f -> OneMinusSrc1
            0x00000010 -> Src1Alpha
            0x00000011 -> OneMinusSrc1Alpha
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
