// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUColorWriteMask(
    public val `value`: Int,
) {
    None(0x00000000),
    Red(0x00000001),
    Green(0x00000002),
    Blue(0x00000004),
    Alpha(0x00000008),
    All(0x0000000F),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUColorWriteMask::class.java,
            "fromInt",
            MethodType.methodType(WGPUColorWriteMask::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUColorWriteMask::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUColorWriteMask = when (value) {
            None.value -> None
            Red.value -> Red
            Green.value -> Green
            Blue.value -> Blue
            Alpha.value -> Alpha
            All.value -> All
            else -> error("enum not found")
        }
    }
}
