// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUCullMode(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    None(0x00000001),
    Front(0x00000002),
    Back(0x00000003),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUCullMode::class.java,
            "fromInt",
            MethodType.methodType(WGPUCullMode::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUCullMode::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUCullMode = when (value) {
            0x00000000 -> Undefined
            0x00000001 -> None
            0x00000002 -> Front
            0x00000003 -> Back
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
