// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUPopErrorScopeCallbackInfo(
    public val `$mem`: MemorySegment,
) {
    public var nextInChain: Pointer<WGPUChainedStruct>
        get() = WGPUPopErrorScopeCallbackInfo.nextInChainHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUPopErrorScopeCallbackInfo.nextInChainHandle.set(this.`$mem`, 0L, value)
        }

    public var mode: WGPUCallbackMode
        get() = WGPUCallbackMode.fromInt(
            WGPUPopErrorScopeCallbackInfo.modeHandle.get(this.`$mem`, 0L)
                    as Int
        )
        set(`value`) {
            WGPUPopErrorScopeCallbackInfo.modeHandle.set(this.`$mem`, 0L, value.value)
        }

    public var callback: WGPUPopErrorScopeCallback
        get() = WGPUPopErrorScopeCallbackInfo.callbackHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUPopErrorScopeCallbackInfo.callbackHandle.set(this.`$mem`, 0L, value)
        }

    public var oldCallback: WGPUErrorCallback
        get() = WGPUPopErrorScopeCallbackInfo.oldCallbackHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUPopErrorScopeCallbackInfo.oldCallbackHandle.set(this.`$mem`, 0L, value)
        }

    public var userdata: Pointer<Unit>
        get() = WGPUPopErrorScopeCallbackInfo.userdataHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUPopErrorScopeCallbackInfo.userdataHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUPopErrorScopeCallbackInfo.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("nextInChain"),
            ValueLayout.JAVA_INT.withName("mode"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
            `$RuntimeHelper`.POINTER.withName("callback"),
            `$RuntimeHelper`.POINTER.withName("oldCallback"),
            `$RuntimeHelper`.POINTER.withName("userdata"),
        ).withName("WGPUPopErrorScopeCallbackInfo")

        @JvmField
        public val nextInChainHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("nextInChain"))

        @JvmField
        public val modeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("mode"))

        @JvmField
        public val callbackHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("callback"))

        @JvmField
        public val oldCallbackHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("oldCallback"))

        @JvmField
        public val userdataHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("userdata"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUPopErrorScopeCallbackInfo =
            WGPUPopErrorScopeCallbackInfo(alloc.allocate(WGPUPopErrorScopeCallbackInfo.layout))

        public fun interface callback {
            public fun invoke(
                status: WGPUPopErrorScopeStatus,
                type: WGPUErrorType,
                message: Pointer<Byte>,
                userdata: Pointer<Unit>,
            )

            public fun allocate(arena: Arena): MemorySegment =
                Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

            public companion object {
                @JvmStatic
                public val invokeHandle: MethodHandle =
                    MethodHandles.filterArguments(
                        MethodHandles.lookup().unreflect(callback::class.java.methods.find {
                            it.name == "invoke"
                        }
                        ),
                        1, WGPUPopErrorScopeStatus.fromInt, WGPUErrorType.fromInt, null, null,
                    )

                @JvmStatic
                public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
                    ValueLayout.JAVA_INT,
                    ValueLayout.JAVA_INT,
                    `$RuntimeHelper`.POINTER,
                    `$RuntimeHelper`.POINTER,
                )
            }
        }

        public fun interface oldCallback {
            public fun invoke(
                type: WGPUErrorType,
                message: Pointer<Byte>,
                userdata: Pointer<Unit>,
            )

            public fun allocate(arena: Arena): MemorySegment =
                Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

            public companion object {
                @JvmStatic
                public val invokeHandle: MethodHandle =
                    MethodHandles.filterArguments(
                        MethodHandles.lookup().unreflect(oldCallback::class.java.methods.find {
                            it.name == "invoke"
                        }
                        ),
                        1, WGPUErrorType.fromInt, null, null,
                    )

                @JvmStatic
                public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
                    ValueLayout.JAVA_INT,
                    `$RuntimeHelper`.POINTER,
                    `$RuntimeHelper`.POINTER,
                )
            }
        }
    }
}
