// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUColorWriteMask(
    public val `value`: Int,
) {
    None(0x00000000),
    Red(0x00000001),
    Green(0x00000002),
    Blue(0x00000004),
    Alpha(0x00000008),
    All(0x0000000f),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUColorWriteMask::class.java,
            "fromInt",
            MethodType.methodType(WGPUColorWriteMask::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUColorWriteMask::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUColorWriteMask = when (value) {
            0x00000000 -> None
            0x00000001 -> Red
            0x00000002 -> Green
            0x00000004 -> Blue
            0x00000008 -> Alpha
            0x0000000f -> All
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
