// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUWGSLFeatureName(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    ReadonlyAndReadwriteStorageTextures(0x00000001),
    Packed4x8IntegerDotProduct(0x00000002),
    UnrestrictedPointerParameters(0x00000003),
    PointerCompositeAccess(0x00000004),
    ChromiumTestingUnimplemented(0x000003e8),
    ChromiumTestingUnsafeExperimental(0x000003e9),
    ChromiumTestingExperimental(0x000003ea),
    ChromiumTestingShippedWithKillswitch(0x000003eb),
    ChromiumTestingShipped(0x000003ec),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUWGSLFeatureName::class.java,
            "fromInt",
            MethodType.methodType(WGPUWGSLFeatureName::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUWGSLFeatureName::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUWGSLFeatureName = when (value) {
            0x00000000 -> Undefined
            0x00000001 -> ReadonlyAndReadwriteStorageTextures
            0x00000002 -> Packed4x8IntegerDotProduct
            0x00000003 -> UnrestrictedPointerParameters
            0x00000004 -> PointerCompositeAccess
            0x000003e8 -> ChromiumTestingUnimplemented
            0x000003e9 -> ChromiumTestingUnsafeExperimental
            0x000003ea -> ChromiumTestingExperimental
            0x000003eb -> ChromiumTestingShippedWithKillswitch
            0x000003ec -> ChromiumTestingShipped
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
