// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUProgrammableStageDescriptor(
    public val `$mem`: MemorySegment,
) {
    public var nextInChain: Pointer<WGPUChainedStruct>
        get() = WGPUProgrammableStageDescriptor.nextInChainHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUProgrammableStageDescriptor.nextInChainHandle.set(this.`$mem`, 0L, value)
        }

    public var module: WGPUShaderModule
        get() = WGPUProgrammableStageDescriptor.moduleHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUProgrammableStageDescriptor.moduleHandle.set(this.`$mem`, 0L, value)
        }

    public var entryPoint: Pointer<Byte>
        get() = WGPUProgrammableStageDescriptor.entryPointHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUProgrammableStageDescriptor.entryPointHandle.set(this.`$mem`, 0L, value)
        }

    public var constantCount: ULong
        get() = (WGPUProgrammableStageDescriptor.constantCountHandle.get(this.`$mem`, 0L) as
                Long).toULong()
        set(`value`) {
            WGPUProgrammableStageDescriptor.constantCountHandle.set(this.`$mem`, 0L, value.toLong())
        }

    public var constants: Pointer<WGPUConstantEntry>
        get() = WGPUProgrammableStageDescriptor.constantsHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUProgrammableStageDescriptor.constantsHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUProgrammableStageDescriptor.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("nextInChain"),
            `$RuntimeHelper`.POINTER.withName("module"),
            `$RuntimeHelper`.POINTER.withName("entryPoint"),
            ValueLayout.JAVA_LONG.withName("constantCount"),
            `$RuntimeHelper`.POINTER.withName("constants"),
        ).withName("WGPUProgrammableStageDescriptor")

        @JvmField
        public val nextInChainHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("nextInChain"))

        @JvmField
        public val moduleHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("module"))

        @JvmField
        public val entryPointHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("entryPoint"))

        @JvmField
        public val constantCountHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("constantCount"))

        @JvmField
        public val constantsHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("constants"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUProgrammableStageDescriptor =
            WGPUProgrammableStageDescriptor(alloc.allocate(WGPUProgrammableStageDescriptor.layout))
    }
}
