// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUTextureUsage(
    public val `value`: Int,
) {
    None(0x00000000),
    CopySrc(0x00000001),
    CopyDst(0x00000002),
    TextureBinding(0x00000004),
    StorageBinding(0x00000008),
    RenderAttachment(0x00000010),
    TransientAttachment(0x00000020),
    StorageAttachment(0x00000040),
    Force32(0x7fffffff),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUTextureUsage::class.java,
            "fromInt",
            MethodType.methodType(WGPUTextureUsage::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUTextureUsage::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUTextureUsage = when (value) {
            0x00000000 -> None
            0x00000001 -> CopySrc
            0x00000002 -> CopyDst
            0x00000004 -> TextureBinding
            0x00000008 -> StorageBinding
            0x00000010 -> RenderAttachment
            0x00000020 -> TransientAttachment
            0x00000040 -> StorageAttachment
            0x7fffffff -> Force32
            else -> error("enum not found")
        }
    }
}
