// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int
import kotlin.jvm.JvmStatic
import webgpu.WGPUBufferBindingType.ReadOnlyStorage
import webgpu.WGPUBufferBindingType.Storage
import webgpu.WGPUBufferBindingType.Undefined
import webgpu.WGPUBufferBindingType.Uniform

public enum class WGPUBufferBindingType(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    Uniform(0x00000001),
    Storage(0x00000002),
    ReadOnlyStorage(0x00000003),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUBufferBindingType::class.java,
            "fromInt",
            MethodType.methodType(WGPUBufferBindingType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUBufferBindingType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUBufferBindingType = when (value) {
            Undefined.value -> Undefined
            Uniform.value -> Uniform
            Storage.value -> Storage
            ReadOnlyStorage.value -> ReadOnlyStorage
            else -> error("enum not found")
        }
    }
}
