// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUSharedTextureMemoryIOSurfaceDescriptor(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStruct
        get() =
            WGPUChainedStruct(
                WGPUSharedTextureMemoryIOSurfaceDescriptor.chainHandle.invokeExact(
                    this.`$mem`,
                    0L
                ) as MemorySegment
            )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStruct.layout.byteSize()
            )
        }

    public var ioSurface: Pointer<Unit>
        get() = WGPUSharedTextureMemoryIOSurfaceDescriptor.ioSurfaceHandle.get(this.`$mem`, 0L) as
                MemorySegment
        set(`value`) {
            WGPUSharedTextureMemoryIOSurfaceDescriptor.ioSurfaceHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUSharedTextureMemoryIOSurfaceDescriptor.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStruct.layout.withName("chain"),
            `$RuntimeHelper`.POINTER.withName("ioSurface"),
        ).withName("WGPUSharedTextureMemoryIOSurfaceDescriptor")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val ioSurfaceHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("ioSurface"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUSharedTextureMemoryIOSurfaceDescriptor =
            WGPUSharedTextureMemoryIOSurfaceDescriptor(alloc.allocate(WGPUSharedTextureMemoryIOSurfaceDescriptor.layout))
    }
}
