// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c.proc

import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemorySegment
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import kotlin.jvm.JvmStatic
import webgpu.c.Pointer
import webgpu.c.WGPUCommandEncoder
import webgpu.c.WGPUExtent3D
import webgpu.c.WGPUTexelCopyBufferInfo
import webgpu.c.WGPUTexelCopyTextureInfo
import webgpu.c.`$RuntimeHelper`

public fun interface WGPUProcCommandEncoderCopyBufferToTexture {
    public fun invoke(
        commandEncoder: WGPUCommandEncoder,
        source: Pointer<WGPUTexelCopyBufferInfo>,
        destination: Pointer<WGPUTexelCopyTextureInfo>,
        copySize: Pointer<WGPUExtent3D>,
    )

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(WGPUProcCommandEncoderCopyBufferToTexture::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
