// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int
import kotlin.jvm.JvmStatic
import webgpu.c.WGPUStatus.Error
import webgpu.c.WGPUStatus.Success

public enum class WGPUStatus(
    public val `value`: Int,
) {
    Success(0x00000001),
    Error(0x00000002),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUStatus::class.java,
            "fromInt",
            MethodType.methodType(WGPUStatus::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUStatus::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUStatus = when (value) {
            Success.value -> Success
            Error.value -> Error
            else -> error("enum not found")
        }
    }
}
