// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int
import kotlin.jvm.JvmStatic
import webgpu.c.WGPUSType.RenderPassMaxDrawCount
import webgpu.c.WGPUSType.ShaderSourceSPIRV
import webgpu.c.WGPUSType.ShaderSourceWGSL
import webgpu.c.WGPUSType.SurfaceSourceAndroidNativeWindow
import webgpu.c.WGPUSType.SurfaceSourceMetalLayer
import webgpu.c.WGPUSType.SurfaceSourceWaylandSurface
import webgpu.c.WGPUSType.SurfaceSourceWindowsHWND
import webgpu.c.WGPUSType.SurfaceSourceXCBWindow
import webgpu.c.WGPUSType.SurfaceSourceXlibWindow

public enum class WGPUSType(
    public val `value`: Int,
) {
    ShaderSourceSPIRV(0x00000001),
    ShaderSourceWGSL(0x00000002),
    RenderPassMaxDrawCount(0x00000003),
    SurfaceSourceMetalLayer(0x00000004),
    SurfaceSourceWindowsHWND(0x00000005),
    SurfaceSourceXlibWindow(0x00000006),
    SurfaceSourceWaylandSurface(0x00000007),
    SurfaceSourceAndroidNativeWindow(0x00000008),
    SurfaceSourceXCBWindow(0x00000009),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUSType::class.java,
            "fromInt",
            MethodType.methodType(WGPUSType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUSType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUSType = when (value) {
            ShaderSourceSPIRV.value -> ShaderSourceSPIRV
            ShaderSourceWGSL.value -> ShaderSourceWGSL
            RenderPassMaxDrawCount.value -> RenderPassMaxDrawCount
            SurfaceSourceMetalLayer.value -> SurfaceSourceMetalLayer
            SurfaceSourceWindowsHWND.value -> SurfaceSourceWindowsHWND
            SurfaceSourceXlibWindow.value -> SurfaceSourceXlibWindow
            SurfaceSourceWaylandSurface.value -> SurfaceSourceWaylandSurface
            SurfaceSourceAndroidNativeWindow.value -> SurfaceSourceAndroidNativeWindow
            SurfaceSourceXCBWindow.value -> SurfaceSourceXCBWindow
            else -> error("enum not found")
        }
    }
}
