// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.foreign.Arena
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle
import kotlin.Boolean
import kotlin.Int
import kotlin.UInt
import kotlin.Unit
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline
import kotlin.jvm.JvmStatic

@JvmInline
public value class WGPUSurfaceSourceXCBWindow(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStruct
        get() = WGPUChainedStruct(
            WGPUSurfaceSourceXCBWindow.chainHandle.invokeExact(this.`$mem`, 0L) as
                    MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStruct.layout.byteSize()
            )
        }

    public var connection: Pointer<Unit>
        get() = WGPUSurfaceSourceXCBWindow.connectionHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUSurfaceSourceXCBWindow.connectionHandle.set(this.`$mem`, 0L, value)
        }

    public var window: UInt
        get() = (WGPUSurfaceSourceXCBWindow.windowHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            WGPUSurfaceSourceXCBWindow.windowHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUSurfaceSourceXCBWindow.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStruct.layout.withName("chain"),
            `$RuntimeHelper`.POINTER.withName("connection"),
            ValueLayout.JAVA_INT.withName("window"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
        ).withName("WGPUSurfaceSourceXCBWindow")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val connectionHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("connection"))

        @JvmField
        public val windowHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("window"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUSurfaceSourceXCBWindow =
            WGPUSurfaceSourceXCBWindow(alloc.allocate(WGPUSurfaceSourceXCBWindow.layout))
    }
}
