// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int
import kotlin.jvm.JvmStatic
import webgpu.c.WGPUMapAsyncStatus.Aborted
import webgpu.c.WGPUMapAsyncStatus.Error
import webgpu.c.WGPUMapAsyncStatus.InstanceDropped
import webgpu.c.WGPUMapAsyncStatus.Success
import webgpu.c.WGPUMapAsyncStatus.Unknown

public enum class WGPUMapAsyncStatus(
    public val `value`: Int,
) {
    Success(0x00000001),
    InstanceDropped(0x00000002),
    Error(0x00000003),
    Aborted(0x00000004),
    Unknown(0x00000005),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUMapAsyncStatus::class.java,
            "fromInt",
            MethodType.methodType(WGPUMapAsyncStatus::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUMapAsyncStatus::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUMapAsyncStatus = when (value) {
            Success.value -> Success
            InstanceDropped.value -> InstanceDropped
            Error.value -> Error
            Aborted.value -> Aborted
            Unknown.value -> Unknown
            else -> error("enum not found")
        }
    }
}
