// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.foreign.Arena
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.VarHandle
import kotlin.Boolean
import kotlin.Double
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline
import kotlin.jvm.JvmStatic

@JvmInline
public value class WGPUColor(
    public val `$mem`: MemorySegment,
) {
    public var r: Double
        get() = WGPUColor.rHandle.get(this.`$mem`, 0L) as Double
        set(`value`) {
            WGPUColor.rHandle.set(this.`$mem`, 0L, value)
        }

    public var g: Double
        get() = WGPUColor.gHandle.get(this.`$mem`, 0L) as Double
        set(`value`) {
            WGPUColor.gHandle.set(this.`$mem`, 0L, value)
        }

    public var b: Double
        get() = WGPUColor.bHandle.get(this.`$mem`, 0L) as Double
        set(`value`) {
            WGPUColor.bHandle.set(this.`$mem`, 0L, value)
        }

    public var a: Double
        get() = WGPUColor.aHandle.get(this.`$mem`, 0L) as Double
        set(`value`) {
            WGPUColor.aHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUColor.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_DOUBLE.withName("r"),
            ValueLayout.JAVA_DOUBLE.withName("g"),
            ValueLayout.JAVA_DOUBLE.withName("b"),
            ValueLayout.JAVA_DOUBLE.withName("a"),
        ).withName("WGPUColor")

        @JvmField
        public val rHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("r"))

        @JvmField
        public val gHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("g"))

        @JvmField
        public val bHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("b"))

        @JvmField
        public val aHandle: VarHandle = layout.varHandle(MemoryLayout.PathElement.groupElement("a"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUColor =
            WGPUColor(alloc.allocate(WGPUColor.layout))
    }
}
