// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int
import kotlin.jvm.JvmStatic
import webgpu.c.WGPUWGSLLanguageFeatureName.Packed4x8IntegerDotProduct
import webgpu.c.WGPUWGSLLanguageFeatureName.PointerCompositeAccess
import webgpu.c.WGPUWGSLLanguageFeatureName.ReadonlyAndReadwriteStorageTextures
import webgpu.c.WGPUWGSLLanguageFeatureName.UnrestrictedPointerParameters

public enum class WGPUWGSLLanguageFeatureName(
    public val `value`: Int,
) {
    ReadonlyAndReadwriteStorageTextures(0x00000001),
    Packed4x8IntegerDotProduct(0x00000002),
    UnrestrictedPointerParameters(0x00000003),
    PointerCompositeAccess(0x00000004),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUWGSLLanguageFeatureName::class.java,
            "fromInt",
            MethodType.methodType(WGPUWGSLLanguageFeatureName::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUWGSLLanguageFeatureName::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUWGSLLanguageFeatureName = when (value) {
            ReadonlyAndReadwriteStorageTextures.value -> ReadonlyAndReadwriteStorageTextures
            Packed4x8IntegerDotProduct.value -> Packed4x8IntegerDotProduct
            UnrestrictedPointerParameters.value -> UnrestrictedPointerParameters
            PointerCompositeAccess.value -> PointerCompositeAccess
            else -> error("enum not found")
        }
    }
}
