// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUSharedFenceType(
    public val `value`: Int,
) {
    VkSemaphoreOpaqueFD(0x00000001),
    VkSemaphoreSyncFD(0x00000002),
    VkSemaphoreZirconHandle(0x00000003),
    DXGISharedHandle(0x00000004),
    MTLSharedEvent(0x00000005),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUSharedFenceType::class.java,
            "fromInt",
            MethodType.methodType(WGPUSharedFenceType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUSharedFenceType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUSharedFenceType = when (value) {
            VkSemaphoreOpaqueFD.value -> VkSemaphoreOpaqueFD
            VkSemaphoreSyncFD.value -> VkSemaphoreSyncFD
            VkSemaphoreZirconHandle.value -> VkSemaphoreZirconHandle
            DXGISharedHandle.value -> DXGISharedHandle
            MTLSharedEvent.value -> MTLSharedEvent
            else -> error("enum not found")
        }
    }
}
