// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int
import kotlin.jvm.JvmStatic
import webgpu.c.WGPUStencilOperation.DecrementClamp
import webgpu.c.WGPUStencilOperation.DecrementWrap
import webgpu.c.WGPUStencilOperation.IncrementClamp
import webgpu.c.WGPUStencilOperation.IncrementWrap
import webgpu.c.WGPUStencilOperation.Invert
import webgpu.c.WGPUStencilOperation.Keep
import webgpu.c.WGPUStencilOperation.Replace
import webgpu.c.WGPUStencilOperation.Undefined
import webgpu.c.WGPUStencilOperation.Zero

public enum class WGPUStencilOperation(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    Keep(0x00000001),
    Zero(0x00000002),
    Replace(0x00000003),
    Invert(0x00000004),
    IncrementClamp(0x00000005),
    DecrementClamp(0x00000006),
    IncrementWrap(0x00000007),
    DecrementWrap(0x00000008),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUStencilOperation::class.java,
            "fromInt",
            MethodType.methodType(WGPUStencilOperation::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUStencilOperation::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUStencilOperation = when (value) {
            Undefined.value -> Undefined
            Keep.value -> Keep
            Zero.value -> Zero
            Replace.value -> Replace
            Invert.value -> Invert
            IncrementClamp.value -> IncrementClamp
            DecrementClamp.value -> DecrementClamp
            IncrementWrap.value -> IncrementWrap
            DecrementWrap.value -> DecrementWrap
            else -> error("enum not found")
        }
    }
}
