// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.foreign.Arena
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle
import kotlin.Boolean
import kotlin.Double
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline
import kotlin.jvm.JvmStatic

@JvmInline
public value class WGPUConstantEntry(
    public val `$mem`: MemorySegment,
) {
    public var nextInChain: Pointer<WGPUChainedStruct>
        get() = WGPUConstantEntry.nextInChainHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUConstantEntry.nextInChainHandle.set(this.`$mem`, 0L, value)
        }

    public var key: WGPUStringView
        get() = WGPUStringView(
            WGPUConstantEntry.keyHandle.invokeExact(this.`$mem`, 0L) as
                    MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(value.`$mem`, 0L, this.key.`$mem`, 0L, WGPUStringView.layout.byteSize())
        }

    public var `value`: Double
        get() = WGPUConstantEntry.valueHandle.get(this.`$mem`, 0L) as Double
        set(`value`) {
            WGPUConstantEntry.valueHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUConstantEntry.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("nextInChain"),
            WGPUStringView.layout.withName("key"),
            ValueLayout.JAVA_DOUBLE.withName("value"),
        ).withName("WGPUConstantEntry")

        @JvmField
        public val nextInChainHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("nextInChain"))

        @JvmField
        public val keyHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("key"))

        @JvmField
        public val valueHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("value"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUConstantEntry =
            WGPUConstantEntry(alloc.allocate(WGPUConstantEntry.layout))
    }
}
