// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c

import java.lang.foreign.Arena
import java.lang.foreign.MemoryLayout
import java.lang.foreign.MemorySegment
import java.lang.foreign.SegmentAllocator
import java.lang.foreign.StructLayout
import java.lang.foreign.ValueLayout
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle
import kotlin.Boolean
import kotlin.Int
import kotlin.UInt
import kotlin.jvm.JvmField
import kotlin.jvm.JvmInline
import kotlin.jvm.JvmStatic

@JvmInline
public value class WGPUShaderSourceSPIRV(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStruct
        get() = WGPUChainedStruct(
            WGPUShaderSourceSPIRV.chainHandle.invokeExact(this.`$mem`, 0L) as
                    MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStruct.layout.byteSize()
            )
        }

    public var codeSize: UInt
        get() = (WGPUShaderSourceSPIRV.codeSizeHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            WGPUShaderSourceSPIRV.codeSizeHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public var code: Pointer<UInt>
        get() = WGPUShaderSourceSPIRV.codeHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            WGPUShaderSourceSPIRV.codeHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(WGPUShaderSourceSPIRV.layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStruct.layout.withName("chain"),
            ValueLayout.JAVA_INT.withName("codeSize"),
            java.lang.foreign.MemoryLayout.paddingLayout(4),
            `$RuntimeHelper`.POINTER.withName("code"),
        ).withName("WGPUShaderSourceSPIRV")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val codeSizeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("codeSize"))

        @JvmField
        public val codeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("code"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUShaderSourceSPIRV =
            WGPUShaderSourceSPIRV(alloc.allocate(WGPUShaderSourceSPIRV.layout))
    }
}
