// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType

/**
 * TODO
 */
public enum class WGPUBufferBindingType(
    public val `value`: Int,
) {
    /**
     * Indicates that this [WGPUBufferBindingLayout] member of
     * its parent [WGPUBindGroupLayoutEntry] is not used.
     * (See also [SentinelValues](https://webgpu-native.github.io/webgpu-headers/SentinelValues.html).)
     */
    BindingNotUsed(0x00000000),

    /**
     * [1]. Indicates no value is passed for this argument. See [SentinelValues](https://webgpu-native.github.io/webgpu-headers/SentinelValues.html).
     */
    Undefined(0x00000001),

    /**
     * TODO
     */
    Uniform(0x00000002),

    /**
     * TODO
     */
    Storage(0x00000003),

    /**
     * TODO
     */
    ReadOnlyStorage(0x00000004),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUBufferBindingType::class.java,
            "fromInt",
            MethodType.methodType(WGPUBufferBindingType::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUBufferBindingType::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUBufferBindingType = when (value) {
            BindingNotUsed.value -> BindingNotUsed
            Undefined.value -> Undefined
            Uniform.value -> Uniform
            Storage.value -> Storage
            ReadOnlyStorage.value -> ReadOnlyStorage
            else -> error("enum not found")
        }
    }
}
