// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu

import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUShaderSourceSPIRV(
    public val `$mem`: MemorySegment,
) {
    public var chain: WGPUChainedStruct
        get() = WGPUChainedStruct(
            chainHandle.invokeExact(this.`$mem`, 0L) as
                    MemorySegment
        )
        set(`value`) {
            MemorySegment.copy(
                value.`$mem`, 0L, this.chain.`$mem`, 0L,
                WGPUChainedStruct.layout.byteSize()
            )
        }

    public var codeSize: UInt
        get() = (codeSizeHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            codeSizeHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public var code: Pointer<UInt>
        get() = codeHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            codeHandle.set(this.`$mem`, 0L, value)
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            WGPUChainedStruct.layout.withName("chain"),
            ValueLayout.JAVA_INT.withName("codeSize"),
            MemoryLayout.paddingLayout(4),
            `$RuntimeHelper`.POINTER.withName("code"),
        ).withName("WGPUShaderSourceSPIRV")

        @JvmField
        public val chainHandle: MethodHandle =
            layout.sliceHandle(MemoryLayout.PathElement.groupElement("chain"))

        @JvmField
        public val codeSizeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("codeSize"))

        @JvmField
        public val codeHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("code"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUShaderSourceSPIRV =
            WGPUShaderSourceSPIRV(alloc.allocate(layout))
    }
}
