// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class WGPUInstanceCapabilities(
    public val `$mem`: MemorySegment,
) {
    public var nextInChain: Pointer<WGPUChainedStructOut>
        get() = nextInChainHandle.get(this.`$mem`, 0L) as MemorySegment
        set(`value`) {
            nextInChainHandle.set(this.`$mem`, 0L, value)
        }

    public var timedWaitAnyEnable: WGPUBool
        get() = (timedWaitAnyEnableHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            timedWaitAnyEnableHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public var timedWaitAnyMaxCount: ULong
        get() = (timedWaitAnyMaxCountHandle.get(this.`$mem`, 0L) as
                Long).toULong()
        set(`value`) {
            timedWaitAnyMaxCountHandle.set(this.`$mem`, 0L, value.toLong())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            `$RuntimeHelper`.POINTER.withName("nextInChain"),
            ValueLayout.JAVA_INT.withName("timedWaitAnyEnable"),
            MemoryLayout.paddingLayout(4),
            ValueLayout.JAVA_LONG.withName("timedWaitAnyMaxCount"),
        ).withName("WGPUInstanceCapabilities")

        @JvmField
        public val nextInChainHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("nextInChain"))

        @JvmField
        public val timedWaitAnyEnableHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("timedWaitAnyEnable"))

        @JvmField
        public val timedWaitAnyMaxCountHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("timedWaitAnyMaxCount"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): WGPUInstanceCapabilities =
            WGPUInstanceCapabilities(alloc.allocate(layout))
    }
}
