// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPURequestAdapterStatus(
    public val `value`: Int,
) {
    Success(0x00000001),
    InstanceDropped(0x00000002),
    Unavailable(0x00000003),
    Error(0x00000004),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPURequestAdapterStatus::class.java,
            "fromInt",
            MethodType.methodType(WGPURequestAdapterStatus::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPURequestAdapterStatus::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPURequestAdapterStatus = when (value) {
            Success.value -> Success
            InstanceDropped.value -> InstanceDropped
            Unavailable.value -> Unavailable
            Error.value -> Error
            else -> error("enum not found")
        }
    }
}
