// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

public enum class WGPUBlendOperation(
    public val `value`: Int,
) {
    Undefined(0x00000000),
    Add(0x00000001),
    Subtract(0x00000002),
    ReverseSubtract(0x00000003),
    Min(0x00000004),
    Max(0x00000005),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUBlendOperation::class.java,
            "fromInt",
            MethodType.methodType(WGPUBlendOperation::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUBlendOperation::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUBlendOperation = when (value) {
            Undefined.value -> Undefined
            Add.value -> Add
            Subtract.value -> Subtract
            ReverseSubtract.value -> ReverseSubtract
            Min.value -> Min
            Max.value -> Max
            else -> error("enum not found")
        }
    }
}
