// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu

import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles
import java.lang.invoke.MethodType
import kotlin.Int

/**
 * TODO
 */
public enum class WGPUCullMode(
    public val `value`: Int,
) {
    /**
     * Indicates no value is passed for this argument. See [SentinelValues](https://webgpu-native.github.io/webgpu-headers/articles.html).
     */
    Undefined(0x00000000),

    /**
     * TODO
     */
    None(0x00000001),

    /**
     * TODO
     */
    Front(0x00000002),

    /**
     * TODO
     */
    Back(0x00000003),
    ;

    public companion object {
        @JvmStatic
        public val fromInt: MethodHandle = MethodHandles.lookup().findStatic(
            WGPUCullMode::class.java,
            "fromInt",
            MethodType.methodType(WGPUCullMode::class.java, Int::class.java)
        )

        @JvmStatic
        public val toInt: MethodHandle = MethodHandles.lookup().findGetter(
            WGPUCullMode::class.java,
            "value",
            Int::class.java
        )

        @JvmStatic
        public fun fromInt(`value`: Int): WGPUCullMode = when (value) {
            Undefined.value -> Undefined
            None.value -> None
            Front.value -> Front
            Back.value -> Back
            else -> error("enum not found")
        }
    }
}
