package wgpu

public data class GPULimits(
    public var maxTextureDimension1D: UInt = 0U,
    public var maxTextureDimension2D: UInt = 0U,
    public var maxTextureDimension3D: UInt = 0U,
    public var maxTextureArrayLayers: UInt = 0U,
    public var maxBindGroups: UInt = 0U,
    public var maxBindGroupsPlusVertexBuffers: UInt = 0U,
    public var maxBindingsPerBindGroup: UInt = 0U,
    public var maxDynamicUniformBuffersPerPipelineLayout: UInt = 0U,
    public var maxDynamicStorageBuffersPerPipelineLayout: UInt = 0U,
    public var maxSampledTexturesPerShaderStage: UInt = 0U,
    public var maxSamplersPerShaderStage: UInt = 0U,
    public var maxStorageBuffersPerShaderStage: UInt = 0U,
    public var maxStorageTexturesPerShaderStage: UInt = 0U,
    public var maxUniformBuffersPerShaderStage: UInt = 0U,
    public var maxUniformBufferBindingSize: ULong = 0UL,
    public var maxStorageBufferBindingSize: ULong = 0UL,
    public var minUniformBufferOffsetAlignment: UInt = 0U,
    public var minStorageBufferOffsetAlignment: UInt = 0U,
    public var maxVertexBuffers: UInt = 0U,
    public var maxBufferSize: ULong = 0UL,
    public var maxVertexAttributes: UInt = 0U,
    public var maxVertexBufferArrayStride: UInt = 0U,
    public var maxInterStageShaderVariables: UInt = 0U,
    public var maxColorAttachments: UInt = 0U,
    public var maxColorAttachmentBytesPerSample: UInt = 0U,
    public var maxComputeWorkgroupStorageSize: UInt = 0U,
    public var maxComputeInvocationsPerWorkgroup: UInt = 0U,
    public var maxComputeWorkgroupSizeX: UInt = 0U,
    public var maxComputeWorkgroupSizeY: UInt = 0U,
    public var maxComputeWorkgroupSizeZ: UInt = 0U,
    public var maxComputeWorkgroupsPerDimension: UInt = 0U,
)
