package wgpu

public data class GPULimits(
    public var maxTextureDimension1D: UInt = UInt.MAX_VALUE,
    public var maxTextureDimension2D: UInt = UInt.MAX_VALUE,
    public var maxTextureDimension3D: UInt = UInt.MAX_VALUE,
    public var maxTextureArrayLayers: UInt = UInt.MAX_VALUE,
    public var maxBindGroups: UInt = UInt.MAX_VALUE,
    public var maxBindGroupsPlusVertexBuffers: UInt = UInt.MAX_VALUE,
    public var maxBindingsPerBindGroup: UInt = UInt.MAX_VALUE,
    public var maxDynamicUniformBuffersPerPipelineLayout: UInt = UInt.MAX_VALUE,
    public var maxDynamicStorageBuffersPerPipelineLayout: UInt = UInt.MAX_VALUE,
    public var maxSampledTexturesPerShaderStage: UInt = UInt.MAX_VALUE,
    public var maxSamplersPerShaderStage: UInt = UInt.MAX_VALUE,
    public var maxStorageBuffersPerShaderStage: UInt = UInt.MAX_VALUE,
    public var maxStorageTexturesPerShaderStage: UInt = UInt.MAX_VALUE,
    public var maxUniformBuffersPerShaderStage: UInt = UInt.MAX_VALUE,
    public var maxUniformBufferBindingSize: ULong = ULong.MAX_VALUE,
    public var maxStorageBufferBindingSize: ULong = ULong.MAX_VALUE,
    public var minUniformBufferOffsetAlignment: UInt = UInt.MAX_VALUE,
    public var minStorageBufferOffsetAlignment: UInt = UInt.MAX_VALUE,
    public var maxVertexBuffers: UInt = UInt.MAX_VALUE,
    public var maxBufferSize: ULong = ULong.MAX_VALUE,
    public var maxVertexAttributes: UInt = UInt.MAX_VALUE,
    public var maxVertexBufferArrayStride: UInt = UInt.MAX_VALUE,
    public var maxInterStageShaderVariables: UInt = UInt.MAX_VALUE,
    public var maxColorAttachments: UInt = UInt.MAX_VALUE,
    public var maxColorAttachmentBytesPerSample: UInt = UInt.MAX_VALUE,
    public var maxComputeWorkgroupStorageSize: UInt = UInt.MAX_VALUE,
    public var maxComputeInvocationsPerWorkgroup: UInt = UInt.MAX_VALUE,
    public var maxComputeWorkgroupSizeX: UInt = UInt.MAX_VALUE,
    public var maxComputeWorkgroupSizeY: UInt = UInt.MAX_VALUE,
    public var maxComputeWorkgroupSizeZ: UInt = UInt.MAX_VALUE,
    public var maxComputeWorkgroupsPerDimension: UInt = UInt.MAX_VALUE,
)
