// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.wgpu.proc

import lib.wgpu.*
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

/**
 * TODO
 */
public fun interface WGPUPopErrorScopeCallback {
    /**
     * @param status See [WGPUPopErrorScopeStatus].
     * @param type The type of the error caught by the scope, or [WGPUErrorType.NoError] if there was none.
     * If the [status] is not [WGPUPopErrorScopeStatus.Success], this is [WGPUErrorType.NoError].
     * @param message If the [status] is not [WGPUPopErrorScopeStatus.Success] **or**
     * the [type] is not [WGPUErrorType.NoError], this is a non-empty
     * [LocalizableHumanReadableMessageString](https://webgpu-native.github.io/webgpu-headers/articles.html);
     * otherwise, this is an empty string.
     */
    @CFunctionInvoke
    public fun invoke(
        status: WGPUPopErrorScopeStatus,
        type: WGPUErrorType,
        message: WGPUStringView,
        userdata1: Pointer<Unit>,
        userdata2: Pointer<Unit>,
    )

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.filterArguments(
                MethodHandles.lookup().unreflect(WGPUPopErrorScopeCallback::class.java.methods.find {
                    it.getAnnotation(CFunctionInvoke::class.java) != null
                }
                ),
                1, WGPUPopErrorScopeStatus.fromInt, WGPUErrorType.fromInt, null, null, null,
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
            ValueLayout.JAVA_INT,
            ValueLayout.JAVA_INT,
            WGPUStringView.layout,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
