// this file is auto generated by endoqa kotlin ffi, modify it with caution
package webgpu.c.callback

import webgpu.c.`$RuntimeHelper`
import webgpu.c.Pointer
import webgpu.c.WGPUDeviceLostReason
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface WGPUDeviceLostCallback {
    public fun invoke(
        reason: WGPUDeviceLostReason,
        message: Pointer<Byte>,
        userdata: Pointer<Unit>,
    )

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.filterArguments(
                MethodHandles.lookup().unreflect(WGPUDeviceLostCallback::class.java.methods.find {
                    it.name == "invoke"
                }
                ),
                1, WGPUDeviceLostReason.fromInt, null, null,
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
            ValueLayout.JAVA_INT,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
